project:
  type: website
  output-dir: docs

website:
  open-graph:
    image: "https://gera0220.github.io/posts/bienvenida/image.jpg"
  twitter-card:
    creator: "@gera0220"
    image: "https://gera0220.github.io/posts/bienvenida/image.jpg"
    card-style: summary_large_image
  title: "Gerardo Pérez"
  navbar:
    right:
      - blog.qmd
      - href: CV.qmd
        text: CV
      - icon: github
        href: https://github.com/gera0220
      - icon: twitter
        href: https://twitter.com/gera0220
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

