project:
  type: website
  output-dir: docs

link-external-newwindow: true
website:
  repo-url: "https://github.com/gera0220/gera0220.github.io"
  open-graph: true
  twitter-card:
    creator: "@gera0220"
    card-style: summary_large_image
  title: "Gerardo Pérez"
  site-url: "https://gera0220.github.io/"
  navbar:
    right:
      - blog.qmd
      - href: CV.qmd
        text: CV
      - icon: github
        href: https://github.com/gera0220
      - icon: twitter
        href: https://twitter.com/gera0220
      - icon: linkedin
        href: https://www.linkedin.com/in/gera0220
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

