project:
  type: website
  output-dir: docs

website:
  open-graph:
    image: "https://s0.wp.com/i/blank.jpg"
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/gera0220
      - icon: twitter
        href: https://twitter.com/gera0220
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

